name: Build and push docker image of PKC's Agent into Docker Hub repository

on:
  workflow_dispatch: # Putting here is also fine!!
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          push: true
          tags: user/app:latest
          context: ./resources/ansible-docker
          file: ./resources/ansible-docker/dockerfile
